var countries = [
  "Argentina",
  "Australia",
  "Belgium",
  "Brazil",
  "Canada",
  "Switzerland",
  "Chile",
  "China",
  "Czech Republic",
  "Germany",
  "Denmark",
  "Egypt",
  "Spain",
  "Finland",
  "France",
  "United Kingdom",
  "Greece",
  "Hong Kong",
  "Hungary",
  "Indonesia",
  "Ireland",
  "Israel",
  "India",
  "Italy",
  "Jordan",
  "Japan",
  "South Korea",
  "Sri Lanka",
  "Luxembourg",
  "Mexico",
  "Malaysia",
  "Netherlands",
  "Norway",
  "New Zealand",
  "Peru",
  "Philippines",
  "Pakistan",
  "Poland",
  "Portugal",
  "Russia",
  "Sweden",
  "Singapore",
  "Suriname",
  "French Southern Territories",
  "Thailand",
  "Timor-Leste",
  "Tunisia",
  "Turkey",
  "Taiwan, Province Of China",
  "United States of America",
  "Venezuela",
  "Vietnam",
  "South Africa"
];

var sectors = [
  "Basic Materials",
  "Conglomerates",
  "Consumer Goods",
  "Financial",
  "Healthcare",
  "Industrial Goods",
  "Services",
  "Technology",
  "Utilities"
];

var exchanges = [
  "NasdaqCM",
  "NasdaqGM",
  "NasdaqGS",
  "NYSE",
  "NYSE ARCA",
  "NYSE MKT",
  "OTC"
];

var share_filter_tags = [
  ["Exchange", "stock_exchange", ""],
  ["Country", "country", ""],
  ["Sector", "sector", ""],
  ["Market Cap", "marketcap", "USD(mn)"],
  ["Enterprise Value", "enterprisevalue", "USD(mn)"],
  ["Beta", "beta", ""],
  ["Volume", "volume", "mn"],
  ["Dividend Yield (TTM)", "dividendyield", "%"]
];

var fundamental_filter_tags = [
  ["Basic EPS", "basiceps", "USD"],
  ["Diluted EPS", "dilutedeps", "USD"],
  ["EPS growth", "epsgrowth", "%"],
  ["Revenue Growth", "revenuegrowth", "%"],
  ["ROE", "roe", "%"],
  ["ROA", "roa", "%"],
  ["ROIC", "roic", "%"],
  ["Debt-to-Equity", "debttoequity", "%"],
  ["Debt-to-EBITDA", "ltdebttoebitda", "%"],
  ["Gross Margin", "grossmargin", "%"],
  ["EBITDA Margin", "ebitdamargin", "%"],
  ["Net Income Margin", "profitmargin", "%"],
  ["Current Ratio", "currentratio", "x"],
  ["Quick Ratio", "quickratio", "x"],
  ["FCFF Growth", "fcffgrowth", "%"]
];

var valuation_filter_tags = [
  ["PE Ratio", "pricetoearnings", "x"],
  ["Forward PE Ratio", "pricetonextyearearnings", "x"],
  ["Price/Revenue", "pricetorevenue", "x"],
  ["Forward Price/Rev", "pricetonextyearrevenue", "x"],
  ["Price to Book Ratio", "pricetobook", "x"],
  ["EV/EBIT", "evtoebit", "x"],
  ["EV/EBITDA", "evtoebitda", "x"],
  ["EV/FCFF", "evtofcff", "x"],
  ["EV/Invested Capital", "evtoinvestedcapital", "x"],
  ["EV/NOPAT", "evtonopat", "x"],
  ["EV/Operating CF", "evtoocf", "x"],
  ["EV/Revenue", "evtorevenue", "x"]
];

var tag_mapping = {
  "stock_exchange": "Exchange",
  "country": "Country",
  "sector": "Sector",
  "marketcap": "Market Cap",
  "enterprisevalue": "Enterprise Value",
  "beta": "Beta",
  "volume": "Volume",
  "dividendyield": "Dividend Yield (TTM)",
  "basiceps": "Basic EPS",
  "dilutedeps": "Diluted EPS",
  "epsgrowth": "EPS growth",
  "revenuegrowth": "Revenue Growth",
  "roe": "ROE",
  "roa": "ROA",
  "roic": "ROIC",
  "debttoequity": "Debt-to-Equity",
  "ltdebttoebitda": "Debt-to-EBITDA",
  "grossmargin": "Gross Margin",
  "ebitdamargin": "EBITDA Margin",
  "profitmargin": "Net Income Margin",
  "currentratio": "Current Ratio",
  "quickratio": "Quick Ratio",
  "fcffgrowth": "FCFF Growth",
  "pricetoearnings": "PE Ratio",
  "pricetonextyearearnings": "Forward PE Ratio",
  "pricetorevenue": "Price/Revenue",
  "pricetonextyearrevenue": "Forward Price/Rev",
  "pricetobook": "Price to Book Ratio",
  "evtoebit": "EV/EBIT",
  "evtoebitda": "EV/EBITDA",
  "evtofcff": "EV/FCFF",
  "evtoinvestedcapital": "EV/Invested Capital",
  "evtonopat": "EV/NOPAT",
  "evtoocf": "EV/Operating CF",
  "evtorevenue": "EV/Revenue"
}