var countries = [
  "Argentina",
  "Austria",
  "Australia",
  "Belgium",
  "Bahrain",
  "Brazil",
  "Canada",
  "Switzerland",
  "Chile",
  "China",
  "Czech Republic",
  "Germany",
  "Denmark",
  "Egypt",
  "Spain",
  "Finland",
  "France",
  "United Kingdom",
  "Greece",
  "Hong Kong",
  "Hungary",
  "Indonesia",
  "Ireland",
  "Israel",
  "India",
  "Italy",
  "Jordan",
  "Japan",
  "South Korea",
  "Kuwait",
  "Sri Lanka",
  "Luxembourg",
  "Mexico",
  "Malaysia",
  "Netherlands",
  "Norway",
  "New Zealand",
  "Peru",
  "Philippines",
  "Pakistan",
  "Poland",
  "Portugal",
  "Qatar",
  "Russia",
  "Sweden",
  "Singapore",
  "Suriname",
  "French Southern Territories",
  "Thailand",
  "Timor-Leste",
  "Tunisia",
  "Turkey",
  "Taiwan",
  "United States",
  "Venezuela",
  "Vietnam",
  "South Africa"
];

var sectors = [
  "Basic Materials",
  "Conglomerates",
  "Consumer Goods",
  "Financial",
  "Healthcare",
  "Industrial Goods",
  "Services",
  "Technology",
  "Utilities"
];

var fundamental_filter_tags = [
  "basiceps",
  "dilutedeps",
  "epsgrowth",
  "revenuegrowth",
  "roe",
  "roa",
  "roic",
  "debttoequity",
  "grossmargin",
  "ebitdamargin",
  "profitmargin",
  "currentratio",
  "quickratio",
  "fcffgrowth"
];